export const GET_PROFILE = 'GET_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const GET_SKILLS = 'GET_SKILLS';
export const GET_SUBMITTED_SKILLS = 'GET_SUBMITTED_SKILLS';
export const ADD_SUBMITTED_SKILLS = 'ADD_SUBMITTED_SKILLS';
export const REMOVE_SUBMITTED_SKILLS = 'REMOVE_SUBMITTED_SKILLS';